# django-xicon
# Makefile


.ONESHELL:
PHONY: tox test makemessages compilemessages twine-check twine-upload clean help
TEST_PYPI_URL=https://test.pypi.org/legacy/
NAME=xicon
EXTENSIONS=py,html,txt
TRASH=build dist django_xicon.egg-info .tox .mypy_cache
BUILD_TYPES=bdist_wheel sdist

tox:
	tox;\

test:
	./manage.py test $(TESTS);\

makemessages:
	cd $(NAME);\
	for locale in `ls locale`; do\
		django-admin makemessages --locale=$$locale --extension=$(EXTENSIONS);\
	done

compilemessages:
	django-admin compilemessages;\

twine-check:
	python setup.py $(BUILD_TYPES);\
	twine check dist/*;\
	twine upload -s --repository-url $(TEST_PYPI_URL) dist/*;\

twine-upload:
	python setup.py $(BUILD_TYPES);\
	twine upload -s dist/*;\

clean:
	rm -rf $(TRASH);\
	find -type d -name __pycache__ -print0 | xargs -0 rm -rf;\

help:
	@echo "    help:"
	@echo "        Show whis help."
	@echo "    tox:"
	@echo "        Run tox."
	@echo "    test:"
	@echo "        Run tests, can specify tests with 'TESTS' variable."
	@echo "    makemessages:"
	@echo "        Harvest translations."
	@echo "    compilemessages:"
	@echo "        Compile translations."
	@echo "    twine-check:"
	@echo "        Run some twine checks."
	@echo "    twine-upload:"
	@echo "        Uload package to PyPi using twine."
	@echo "    clean:"
	@echo "        Delete useless autogenerated files."
